"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

type Proposal = { surveyId: string; snapshot: string; signature: string; kind: string; operations: Array<{ op: string; questionId?: string; question?: { prompt: string; options?: Array<{ label: string }> }; before?: { prompt: string }; after?: { prompt: string } }>; diagnostics: Array<{ severity: string; title: string; detail: string; questionId?: string }> };
export function SurveyAiPanel({ surveyId, questionId, disabled }: { surveyId: string; questionId?: string; disabled?: boolean }) {
  const router = useRouter(); const [mode, setMode] = useState<"suggest" | "review" | "rewrite">("suggest"); const [text, setText] = useState(""); const [proposal, setProposal] = useState<Proposal | null>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null); const [selected, setSelected] = useState<number[]>([]); const [removals, setRemovals] = useState<number[]>([]);
  async function run() { setPending(true); setMessage(null); try { const response = await fetch("/api/survey-ai", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ surveyId, mode, questionId, ...(mode === "suggest" ? { brief: text } : { instruction: text }) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProposal(data); setSelected(data.operations.map((_: unknown, i: number) => i)); } catch (e) { setMessage(e instanceof Error ? e.message : "دریافت پیشنهاد ناموفق بود."); } finally { setPending(false); } }
  async function apply() { if (!proposal) return; const proposedRemovals = proposal.operations.map((op, i) => op.op === "remove" && selected.includes(i) ? i : -1).filter((i) => i >= 0); if (proposedRemovals.length > 0 && !window.confirm("حذف سؤال انتخاب‌شده قطعی است؟")) return; setRemovals(proposedRemovals); setPending(true); try { const response = await fetch("/api/survey-ai/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ proposal, acceptedOperations: selected, removeOperationIndexes: proposedRemovals, confirmRemovals: proposedRemovals.length > 0 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProposal(null); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : "اعمال پیشنهاد ناموفق بود."); } finally { setPending(false); } }
  if (disabled) return null;
  return <section className="grid gap-3 rounded-md border bg-muted/20 p-4" aria-labelledby="survey-ai-title"><div><h3 id="survey-ai-title" className="font-semibold">کمک با هوش مصنوعی</h3><p className="text-xs text-muted-foreground">پیشنهادها تا وقتی شما نپذیرید روی پیش‌نویس اعمال نمی‌شوند.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="نوع کمک"><Button type="button" size="sm" variant={mode === "suggest" ? "default" : "outline"} onClick={() => setMode("suggest")}>ساخت سؤال از brief</Button><Button type="button" size="sm" variant={mode === "rewrite" ? "default" : "outline"} onClick={() => setMode("rewrite")}>بازنویسی سؤال</Button><Button type="button" size="sm" variant={mode === "review" ? "default" : "outline"} onClick={() => setMode("review")}>بازبینی کل پیش‌نویس</Button></div>{mode !== "review" ? <textarea className="min-h-24 rounded-md border bg-background p-3 text-sm" maxLength={mode === "suggest" ? 4000 : 1200} value={text} onChange={(e) => setText(e.target.value)} placeholder={mode === "suggest" ? "هدف و مخاطب نظرسنجی را کوتاه توضیح دهید…" : "دستور بازنویسی را بنویسید…"} aria-label="دستور فارسی" /> : null}<Button type="button" disabled={pending || (mode !== "review" && !text.trim())} onClick={run}>{pending ? "در حال بررسی…" : "دریافت پیشنهاد"}</Button>{message ? <p role="alert" className="text-sm text-destructive">{message}</p> : null}{proposal ? <div className="grid gap-3 border-t pt-3"><h4 className="font-medium">پیشنهاد قابل بررسی</h4>{proposal.diagnostics.map((d, i) => <div key={i} className="rounded border border-amber-200 bg-amber-50 p-3 text-sm"><strong>{d.title}</strong><p>{d.detail}</p></div>)}{proposal.operations.map((op, i) => <label key={i} className="flex gap-2 rounded border bg-background p-3 text-sm"><input type="checkbox" checked={selected.includes(i)} onChange={(e) => setSelected((v) => e.target.checked ? [...v, i] : v.filter((x) => x !== i))} />{op.op === "add" ? <>افزودن: {op.question?.prompt}</> : <>بازنویسی: {op.before?.prompt} ← {op.after?.prompt}</>}</label>)}<Button type="button" disabled={pending || selected.length === 0} onClick={apply}>پذیرش پیشنهادهای انتخاب‌شده</Button><p className="text-xs text-muted-foreground">حذف‌ها در پذیرش همه اعمال نمی‌شوند و برای هر حذف تأیید جداگانه لازم است.</p></div> : null}</section>;
}
